export const ActionTypes = {
    FETCH_PRODUCTS : "FETCH_PRODUCTS",
    ALL_PRODUCT : "ALL_PRODUCT",
    SELECTED_PRODUCT : "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT : "REMOVE_SELECTED_PRODUCT"
};